resources:
  - url: http://127.0.0.1:5000/big-slider-card.js
    type: module
views:
  - cards:
      - type: custom:big-slider-card
        name: Big Slider Card Development
        entity: sun.sun
        test_gui: true
